# Generated by Django 5.2.7 on 2025-11-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la propiedad', max_digits=10)),
                ('dormitorios', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0, verbose_name='baños')),
                ('garaje', models.PositiveIntegerField(default=0, help_text='Capacidad del garaje (en autos)')),
                ('area', models.PositiveIntegerField(default=0, help_text='Área en metros cuadrados (m²)')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='año de construcción')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('video', models.URLField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL de la Imagen')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='principal.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
            },
        ),
    ]
