# Generated by Django 5.2.8 on 2025-11-30 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='agente_inmobiliario',
            field=models.ForeignKey(blank=True, help_text='Agente responsable de la propiedad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_gestionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='antes_precio_etiqueta',
            field=models.CharField(blank=True, help_text="Ej: 'desde', 'al mes'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveIntegerField(default=0, help_text='Número de baños'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='categoria',
            field=models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('TERRENO', 'Terreno'), ('OFICINA', 'Oficina'), ('LOCAL_COMERCIAL', 'Local Comercial'), ('OTROS', 'Otros')], default='CASA', max_length=50),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='departamento',
            field=models.CharField(default='Lima', help_text='Ej: Lima, Ica', max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='despues_precio_etiqueta',
            field=models.CharField(blank=True, help_text="Ej: 'por mes', 'negociable'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.PositiveIntegerField(default=0, help_text='Número de dormitorios'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_propiedad',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No disponible'), ('NUEVO', 'Nuevo'), ('VENDIDO', 'Vendido'), ('ALQUILADO', 'Alquilado')], default='DISPONIBLE', max_length=50),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='planos_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de los planos de la propiedad', null=True, upload_to='planos/'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('ALQUILER', 'Alquiler'), ('ALQUILER_VENTA', 'Alquiler y Venta'), ('VENTA', 'Venta')], default='VENTA', max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(help_text='Dirección completa de la propiedad', max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ubicacion_url',
            field=models.URLField(blank=True, help_text='URL de Google Maps o similar', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='video',
            field=models.URLField(blank=True, help_text='URL de video de YouTube', max_length=255, null=True),
        ),
    ]
