# Generated by Django 5.2.8 on 2025-11-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_propiedad_agente_inmobiliario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenpropiedad',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen'),
        ),
    ]
