# Generated by Django 5.2.8 on 2025-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_agente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='biografia',
        ),
    ]
