# Generated by Django 5.2.8 on 2025-12-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_agente_biografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='biografia',
            field=models.TextField(blank=True, help_text="Breve descripción para la sección 'Sobre mí'", null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_principal', models.ForeignKey(blank=True, help_text='Este agente será el contacto principal que aparecerá en el pie de página, contacto, etc.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracion_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Web',
                'verbose_name_plural': 'Configuración Web',
            },
        ),
    ]
